/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import codigo.Semantic.SemanticAnalyzer;
import codigo.Semantic.SemanticError;
import codigo.lexer.Token;
import codigo.lexer.TokenProcessor;
import codigo.Sintax.Sintax;
import codigo.lexer.LexicalAnalyzer;
import codigo.lexer.Lexer;
import codigo.lexer.TokenType;
import codigo.translator.SymbolTableEntry;
import codigo.translator.Translator;
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.StringReader;
import java.nio.file.Files;
import java.util.logging.Level;
import java.util.logging.Logger;
import java_cup.runtime.Symbol;
import javax.swing.JFileChooser;
import java.util.List;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Objects;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Charly Ponce
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    } 
    
private void analizarLexico() throws IOException {
    Lexer lexer = new Lexer(new StringReader(txtResultado.getText()));
    LexicalAnalyzer analyzer = new LexicalAnalyzer(lexer);
    TokenProcessor processor = new TokenProcessor();

    List<Token> tokens = new ArrayList<>();
    Token token;
    while ((token = analyzer.nextToken()) != null) {
        tokens.add(token);
    }

    String resultado = processor.processTokens(tokens);
    //txtAnalizarLex.setText(resultado);

    updateLexicalTableModel(tokens);
}


private void generarCodigo() {
    Lexer lexer = new Lexer(new StringReader(txtResultado.getText()));
    List<Token> tokens = new ArrayList<>();
    Token token;
    LexicalAnalyzer analyzer;
    try {
        analyzer = new LexicalAnalyzer(lexer);
        while ((token = analyzer.nextToken()) != null) {
            tokens.add(token);
        }
        Translator translator = new Translator(tokens, this.filePath + this.ASSEMBLY_FILE_EXT);
        translator.translate();
        
        updateSymbolTableModel(translator.getSymbolTable());

        JOptionPane.showMessageDialog(
            null, 
            "El código ensamblador se generó exitosamente.\nUbicación: " + this.filePath + this.ASSEMBLY_FILE_EXT,
            "Generación Exitosa",
            JOptionPane.INFORMATION_MESSAGE
        );

    } catch (IOException ex) {
        JOptionPane.showMessageDialog(
            null, 
            "Ocurrió un error durante la generación del código ensamblador.\nDetalles: " + ex.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE
        );
        Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnArchivo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        btnAnalizarLex = new javax.swing.JButton();
        btnLimpiarLex = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAnalizarSin = new javax.swing.JTextArea();
        btnAnalizarSin = new javax.swing.JButton();
        btnLimpiarSin = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtAnalizarSem = new javax.swing.JTextArea();
        btnAnalizarSemantico = new javax.swing.JButton();
        btnLimpiarSemantico = new javax.swing.JButton();
        btnGenerarCodEnsamblador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setSize(new java.awt.Dimension(720, 1080));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Analizador Lexico", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        btnArchivo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnArchivo.setText("Abrir archivo");
        btnArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchivoActionPerformed(evt);
            }
        });

        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        btnAnalizarLex.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAnalizarLex.setText("Analizar");
        btnAnalizarLex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarLexActionPerformed(evt);
            }
        });

        btnLimpiarLex.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLimpiarLex.setText("Limpiar");
        btnLimpiarLex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarLexActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabla de Símbolos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Tipo", "Ámbito"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Token", "Identificador"
            }
        ));
        jScrollPane6.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAnalizarLex)
                        .addGap(167, 167, 167)
                        .addComponent(btnLimpiarLex))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnArchivo)
                            .addComponent(btnAnalizarLex)
                            .addComponent(btnLimpiarLex))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Analizador Sintactico", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        txtAnalizarSin.setEditable(false);
        txtAnalizarSin.setColumns(20);
        txtAnalizarSin.setRows(5);
        jScrollPane3.setViewportView(txtAnalizarSin);

        btnAnalizarSin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAnalizarSin.setText("Analizar");
        btnAnalizarSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarSinActionPerformed(evt);
            }
        });

        btnLimpiarSin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLimpiarSin.setText("Limpiar");
        btnLimpiarSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarSinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAnalizarSin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpiarSin)
                        .addGap(22, 22, 22))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnalizarSin)
                    .addComponent(btnLimpiarSin))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Analizador Semantico", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        txtAnalizarSem.setEditable(false);
        txtAnalizarSem.setColumns(20);
        txtAnalizarSem.setRows(5);
        jScrollPane5.setViewportView(txtAnalizarSem);

        btnAnalizarSemantico.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAnalizarSemantico.setText("Analizar");
        btnAnalizarSemantico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarSemanticoActionPerformed(evt);
            }
        });

        btnLimpiarSemantico.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLimpiarSemantico.setText("Limpiar");
        btnLimpiarSemantico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarSemanticoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnAnalizarSemantico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpiarSemantico)
                        .addGap(21, 21, 21))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnalizarSemantico)
                    .addComponent(btnLimpiarSemantico))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );

        btnGenerarCodEnsamblador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnGenerarCodEnsamblador.setText("Generar código ensamblador");
        btnGenerarCodEnsamblador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarCodEnsambladorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(507, 507, 507)
                .addComponent(btnGenerarCodEnsamblador)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenerarCodEnsamblador)
                .addGap(44, 44, 44)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchivoActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File archivo = new File(chooser.getSelectedFile().getAbsolutePath());
        this.filename = archivo.getName();
        this.filePath = chooser.getSelectedFile().getAbsolutePath();
        
        try {
            String ST = new String(Files.readAllBytes(archivo.toPath()));
            txtResultado.setText(ST);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnArchivoActionPerformed

    private void btnLimpiarLexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarLexActionPerformed
        // TODO add your handling code here:
        //txtAnalizarLex.setText(null);
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();

        model.setRowCount(0);
    }//GEN-LAST:event_btnLimpiarLexActionPerformed

    private void btnLimpiarSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarSinActionPerformed
        // TODO add your handling code here:
        txtAnalizarSin.setText(null);
    }//GEN-LAST:event_btnLimpiarSinActionPerformed

    private void btnAnalizarLexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarLexActionPerformed
        try {
            analizarLexico();
        } catch (IOException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAnalizarLexActionPerformed

    private void btnAnalizarSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarSinActionPerformed
        String ST = txtResultado.getText();
        List<String> errores = new ArrayList<>();

        // Instanciar el parser (Sintax) con el lexer
        Sintax s = new Sintax(new codigo.lexer.LexerCup(new StringReader(ST)));

        // Variable para controlar el ciclo de análisis
        int inicioAnalisis = 0;
        boolean analizando = true;
        int linea = 0;
        int columna = 0;

        while (analizando) {
            try {
                // Obtener el texto a analizar, comenzando desde el índice actual
                String textoAnalizar = ST.substring(inicioAnalisis);
                s = new Sintax(new codigo.lexer.LexerCup(new StringReader(textoAnalizar)));

                // Intentar hacer el parseo del texto
                s.parse();

                // Si no hay errores, mostrar mensaje de éxito
                txtAnalizarSin.setText("Análisis realizado correctamente");
                txtAnalizarSin.setForeground(new Color(25, 111, 61));
                analizando = false;  // Detener el ciclo si el análisis es exitoso
            } catch (Exception ex) {
                // Si hay un error, obtenemos el símbolo (error)
                Symbol sym = s.getS();

                //Ajustamos los valores de referencia para mostrar el error
                columna += sym.left + 1;
                linea += sym.right + 1;
                String textoError ="";
                if(Objects.isNull(sym.value)){textoError = "Error cierre de llaves";}
                else {textoError = (String) sym.value;}
                // Capturar el error y agregarlo a la lista de errores
                String error = "Error de sintaxis. Línea: " + (linea) + 
                               " Columna: " + (columna) + 
                               ", Texto: \"" + textoError + "\"";
                errores.add(error);
                
                columna += (sym.value+"").length();

                // Dividir el texto en líneas
                String[] lineas = ST.split("\n");
                int totalLineas = lineas.length;
                int lineaError = sym.right +1;
                if(lineaError == 0){lineaError=1;}

                if (lineaError  < totalLineas) {
                    // Si el error no está en la última línea, continuar con el texto de las siguientes lineas
                    // Unir las líneas desde el índice seleccionado hacia adelante
                    String nuevoTexto = String.join("\n", Arrays.copyOfRange(lineas, lineaError, totalLineas));
                    ST = nuevoTexto;
                } else {
                    // Si estamos en la última línea, detener el ciclo
                    analizando = false;
                }
            }
        }

        // Mostrar todos los errores encontrados en el JTextField al final
        StringBuilder sb = new StringBuilder();
        for (String errorMsg : errores) {
            sb.append(errorMsg).append("\n");
        }
        
        if(errores.size()>0){
        // Mostrar todos los errores en el txtAnalizarSin
        txtAnalizarSin.setText(sb.toString());
        txtAnalizarSin.setForeground(Color.red);
        }
    }//GEN-LAST:event_btnAnalizarSinActionPerformed

    private void btnGenerarCodEnsambladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarCodEnsambladorActionPerformed
        // TODO add your handling code here:
        this.generarCodigo();
    }//GEN-LAST:event_btnGenerarCodEnsambladorActionPerformed

    private void btnLimpiarSemanticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarSemanticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarSemanticoActionPerformed

    private void btnAnalizarSemanticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarSemanticoActionPerformed
        try {
            String ST = txtResultado.getText();  // Obtener el texto de entrada del JTextArea
            List<SemanticError> erroresSemanticos = new ArrayList<>();  // Lista para recolectar errores semánticos

            // Crear el lexer y parser
            Lexer lexer = new Lexer(new StringReader(ST));
            LexicalAnalyzer lexicalAnalyzer = new LexicalAnalyzer(lexer);
            Sintax parser = new Sintax(new codigo.lexer.LexerCup(new StringReader(ST)));

            // Crear el analizador semántico y la tabla de símbolos
            SemanticAnalyzer semanticAnalyzer = new SemanticAnalyzer();

            try {
                // Ejecutar el análisis sintáctico y semántico
                parser.parse();

                // Realizar el análisis léxico y agregar tokens a la tabla de símbolos
                Token token;
                while ((token = lexicalAnalyzer.nextToken()) != null) {
                    if (token.getType() == TokenType.VARIABLE_DECLARATION) {
                        semanticAnalyzer.declareVariable(token.getLexeme(), "int", token.getLine());
                    } else if (token.getType() == TokenType.USE_VARIABLE) {
                        semanticAnalyzer.checkVariableDefined(token.getLexeme(), token.getLine());
                    } else if (token.getType() == TokenType.BREAK_STATEMENT) {
                        semanticAnalyzer.checkBreakUsage(token.getLine());
                    } else if (token.getType() == TokenType.CONTINUE_STATEMENT) {
                        semanticAnalyzer.checkContinueUsage(token.getLine());
                    }
                }

                // Ejecutar optimizaciones
                semanticAnalyzer.checkConstantFolding(null, 0);  // Implementación de ejemplo
                semanticAnalyzer.checkConstantPropagation();

                // Obtener errores semánticos y agregarlos a la lista
                erroresSemanticos.addAll(semanticAnalyzer.getErrors());

                // Mostrar los errores semánticos en el JTextField
                if (erroresSemanticos.isEmpty()) {
                    txtAnalizarSem.setText("Análisis semántico realizado correctamente. No se encontraron errores.");
                    txtAnalizarSem.setForeground(new Color(25, 111, 61));
                } else {
                    StringBuilder sb = new StringBuilder();
                    for (SemanticError errorMsg : erroresSemanticos) {
                        sb.append(errorMsg.toString()).append("\n");
                    }
                    txtAnalizarSem.setText(sb.toString());
                    txtAnalizarSem.setForeground(Color.red);
                }

            } catch (Exception ex) {
                Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                txtAnalizarSem.setText("Error en el análisis semántico: " + ex.getMessage());
                txtAnalizarSem.setForeground(Color.red);
            }
        } catch (IOException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAnalizarSemanticoActionPerformed
    
    private void updateLexicalTableModel(List<Token> tokens) {
    DefaultTableModel model = (DefaultTableModel) jTable2.getModel();

    model.setRowCount(0);
    for (Token token : tokens) {
        model.addRow(new Object[]{
            token.getType(),
            token.getLexeme()
        });
    }
}

    
    private void displaySymbolTable(List<SymbolTableEntry> symbolTable) {
    // Columnas de la tabla
    String[] columnNames = {"Nombre", "Tipo", "Ámbito"};

    // Datos de la tabla
    String[][] data = new String[symbolTable.size()][3];
    for (int i = 0; i < symbolTable.size(); i++) {
        SymbolTableEntry entry = symbolTable.get(i);
        data[i][0] = entry.getName();
        data[i][1] = entry.getType();
        data[i][2] = entry.getScope();
    }

    JTable table = new JTable(data, columnNames);
    table.setEnabled(false);

    JScrollPane scrollPane = new JScrollPane(table);
    JOptionPane.showMessageDialog(
            null,
            scrollPane,
            "Tabla de Símbolos",
            JOptionPane.INFORMATION_MESSAGE
    );
}

    private void updateSymbolTableModel(List<SymbolTableEntry> symbolTable) {
    // Obtener el modelo actual de la tabla
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    
    // Limpiar cualquier dato existente
    model.setRowCount(0);

    // Agregar las filas desde la lista de la tabla de símbolos
    for (SymbolTableEntry entry : symbolTable) {
        model.addRow(new Object[]{
            entry.getName(),
            entry.getType(),
            entry.getScope()
        });
    }
}

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    private String filename;
    private final String ASSEMBLY_FILE_EXT = ".asm";
    private String filePath;

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalizarLex;
    private javax.swing.JButton btnAnalizarSemantico;
    private javax.swing.JButton btnAnalizarSin;
    private javax.swing.JButton btnArchivo;
    private javax.swing.JButton btnGenerarCodEnsamblador;
    private javax.swing.JButton btnLimpiarLex;
    private javax.swing.JButton btnLimpiarSemantico;
    private javax.swing.JButton btnLimpiarSin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea txtAnalizarSem;
    private javax.swing.JTextArea txtAnalizarSin;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
